
include("indicesarray.jl")
include("iarray.jl")
include("similar.jl")
include("getindex.jl")
include("broadcasting.jl")
include("setindex.jl")
include("operators.jl")
include("rebuild.jl")
include("reduce.jl")
include("dimensions.jl")
include("appends.jl")
include("push_pop.jl")
include("math.jl")
include("stats.jl")
include("show.jl")
